version: '2.1'

services: 

  ui:
    build:
      context: ./ui
    ports:
      - '80:80'
    networks: 
      - 'dotnet_solution_network'
    depends_on:
      - api
      - database

  api: 
    build: 
      context: ./api
    ports:
      - '8111:80'
    environment: 
      - ASPNETCORE_ENVIRONMENT=Container
    networks: 
      - 'dotnet_solution_network'
    depends_on:
      - database

  database:
    image: mongo:3
    environment:
      - MONGO_INITDB_DATABASE:apidb
    volumes:
      - ./.data/mongo:/data/db
    networks: 
      - 'dotnet_solution_network'

networks: 
  dotnet_solution_network:
    driver: bridge
