using System.ComponentModel.DataAnnotations;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace api.Models
{
    public class Todo
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }                
        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public string Id { get; set; }   
        [Required]
        public string Description { get; set; }
        public bool? Done { get; set; }
    }
}